functions.py: fix test failure with pandas 2.0
As seen in [Debian bug #1044070], the module pauvre sees the below
test failure:

	  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pauvre/build/pauvre/functions.py", line 75, in __init__
	    self.features.drop('dunno1', 1, inplace=True)
	TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

Upon analysis, this looks to be caused by a subtle but fatal (and
unfortunately undocumented) change in pandas.DataFram.drop signature.
Explicitly specifying the axis= argument looks to correct the issue.

[Debian bug #1044070]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1044070

Signed-off-by: Étienne Mollier <emollier@debian.org>